
sudo: false

install:
    - "wget https://github.com/lh3/minimap2/releases/download/v2.10/minimap2-2.10_x64-linux.tar.bz2"
    - "tar xvf minimap2-2.10_x64-linux.tar.bz2"
    - "export PATH=$PWD/bin:$PWD/minimap2-2.10_x64-linux:$PATH"

script:
    - "sixess -V"
    - "sixess -h"
    - "! sixess -x"
    - "sixess 2>&1 | grep ERROR"
    - "sixess test/R1.fq.gz"
    - "sixess -q test/contigs.fa"
    - "sixess -q - < test/contigs.fa"
    - "rm -f out.paf && sixess -q -m out.paf test/contigs.fa && wc -l out.paf && rm -f out.paf"
    - "cat test/R1.fq.gz | sixess -q -t 4 -"
    - "sixess test/contigs.fa | grep 'Streptococcus pyogenes'"
    - "sixess -d NOTEXIST test/R1.fq.gz 2>&1 | grep ERROR"
    - "sixess -t 2 -d NCBI test/R1.fq.gz"
    - "sixess -q -t 4 test/R1.fq.gz test/R1.fq.gz | grep 'epidermidis'"
    - "sixess /dev/null | grep 'No matches'"
    - "sixess -d SILVA.gz -t 4 test/R1.fq.gz"
